name: Component Visual Regression Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  component_visual_regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd login_page
          pnpm install

      - name: Build Storybook
        run: |
          cd login_page
          pnpm run build-storybook

      - name: Publish to Chromatic
        run: |
          cd login_page
          npx chromatic --project-token=chpt_97d01c841cd9b3c --exit-zero-on-changes
